version: '3.8'

services:
  db:
    container_name: hackathon_db
    image: mysql/mysql-server:latest
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}