version: '3.8'

services:
  db:
    container_name: hackathon_db
    image: mysql/mysql-server:latest
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql
      
  whisper-ai:
    container_name: whisper_ai
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - whisper-data:/python-docker

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

volumes:
  mysql-data: {}
  whisper-data: {}
  ollama-data: {}